name: swen_test_mobile_app
description: Swen Test Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.6
  modal_bottom_sheet: ^3.0.0-pre


dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^6.3.0


dependency_overrides:
  analyzer: ^6.3.0
  meta: ^1.11.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700

        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500

        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400

        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300

